package ethos.model.content.achievement;

/**
 * 
 * @author Jason http://www.rune-server.org/members/jason
 * @date Mar 27, 2014
 */
public enum AchievementType {

	/*
	 * PVM
	 */
	SLAY_ROCK_CRABS, SLAY_CHICKENS, SLAY_ANY_NPCS, SLAY_BABY_DRAGONS, SLAY_DRAGONS, SLAY_BOSSES, VORKATH, CERB, ZULRAH, 

	/*
	 * Skill
	 */
	FISH, COOK, MINE, SMITH, FARM, HERB, WOODCUT, FLETCH, FIRE, THIEV, AGIL, ROOFTOP, SLAY, RUNECRAFTING, MINE_ADAMANT, MINE_RUNE, FISH_SWORDFISH, FISH_SHARK, PRAYER,

	/*
	 * Complete minigames/Crystal chest
	 */
	// Tier 1
	LOOT_CRYSTAL_CHEST, PEST_CONTROL_ROUNDS, FIGHT_CAVES_ROUNDS, SLAYER_CHEST, RAIDS, TOB, MAGE_ARENA,

	/*
	 * Others
	 */
	CLUES, DEAL_DAMAGE_PVM, HEAL_WITH_FOOD, WEAR_MAX, WEAR_99, ARMOUR, DUEL_WINNER, MBOX, ULTRA, VOTEBOX, JAR, SKILLINGCRATE, VOTE, SCRATCH, BLOODMONEY, BANKPIN, EVENTBOSS, GAINS, GAMBLE, ASSAULT, DAWN, RFD, SHOPPER, HASTA, RAIDBOX, KARILS, AHRIMS, DHAROKS, GUTHANS, VERACS, TORAGS, PERK, BLOODALTAR, GODSWORD, SPIRITSHIELD, IMBUERING

}
